# Learning Box Embeddings (Tensorflow version) with Example

This tutorial outlines the different functionalities available within the Box Embeddings package

### 0. Installing the package on your machine

*If you have the repo cloned*
```
pip install --editable . --user
```

### A. Initialize a box tensor and check its parameters

#### Standard Box Tensor
To represent a Tensor as a Box, we use the class `BoxTensor`. The necessary parameter is `data` (a tensor)

In [14]:
import tensorflow as tf
import numpy as np
from box_embeddings.parameterizations.tf_box_tensor import TFBoxTensor
# Let's create a toy example
tensor = tf.constant(np.random.rand(3, 2, 5))

box_1 = TFBoxTensor(tensor)
box_1

TFBoxTensor(<tf.Tensor: shape=(3, 2, 5), dtype=float64, numpy=
array([[[0.3190189 , 0.40414471, 0.7793904 , 0.23254109, 0.77295531],
        [0.63826379, 0.66994828, 0.19170884, 0.49829891, 0.51727324]],

       [[0.18452155, 0.55675524, 0.33556427, 0.1643034 , 0.2435918 ],
        [0.42749645, 0.42918984, 0.91058294, 0.75946523, 0.56404603]],

       [[0.74176181, 0.98326877, 0.96255359, 0.50936529, 0.27783447],
        [0.81371884, 0.88146877, 0.9981995 , 0.75038933, 0.42585809]]])>)

We can use several methods to look at the parameters of our box, such as

In [15]:
# Lower left coordinate
print(box_1.z)
# Top right coordinate
print(box_1.Z)
# Center coordinate
print(box_1.centre)

tf.Tensor(
[[0.3190189  0.40414471 0.7793904  0.23254109 0.77295531]
 [0.18452155 0.55675524 0.33556427 0.1643034  0.2435918 ]
 [0.74176181 0.98326877 0.96255359 0.50936529 0.27783447]], shape=(3, 5), dtype=float64)
tf.Tensor(
[[0.63826379 0.66994828 0.19170884 0.49829891 0.51727324]
 [0.42749645 0.42918984 0.91058294 0.75946523 0.56404603]
 [0.81371884 0.88146877 0.9981995  0.75038933 0.42585809]], shape=(3, 5), dtype=float64)
tf.Tensor(
[[0.47864134 0.5370465  0.48554962 0.36542    0.64511428]
 [0.306009   0.49297254 0.62307361 0.46188432 0.40381892]
 [0.77774033 0.93236877 0.98037654 0.62987731 0.35184628]], shape=(3, 5), dtype=float64)


Let's broadcast our box to a new shape.. Broadcasting is often needed for different arithmetic operations. The function we
will use is `broadcast()`, and the required parameter is `target_shape=()`, which specify the new shape
for the box. This is very similar to `numpy.broadcast_to()`

In [22]:
tensor = tf.constant(np.random.rand(3, 2, 5))

box_1 = TFBoxTensor(tensor)
print('previous shape is:', box_1.box_shape)

box_1.broadcast(target_shape=(3, 1, 5))
print('after broadcasting:', box_1.box_shape)

previous shape is: (3, 5)
after broadcasting: (3, 1, 5)


### 2. Box Volume - TODO (waiting for Tf version)
To calculate the volume of a box, we can use
To ensure numerical stability, we can use the log version

In [77]:
from box_embeddings.modules.volume.soft_volume import soft_volume, log_soft_volume
from box_embeddings.modules.volume.bessel_volume import bessel_volume_approx, log_bessel_volume_approx

# Create data as tensors, and initialize a box
tensor = tf.constant(np.random.rand(3, 2, 5))

box_1 = TFBoxTensor(tensor)
box_1

# Soft volume - TODO



tensor(2.4414e+16)
tensor(37.7339)


### 3. Box Intersection - TODO (waiting for Tf version)

To calculate the intersection of two boxes (which yields a box), we can use

In [78]:
from box_embeddings.modules.intersection import hard_intersection, gumbel_intersection

# Create data as tensors, and initialize two boxes, box_1 and box_2
tensor1 = tf.constant(np.random.rand(3, 2, 5))
tensor2 = tf.constant(np.random.rand(3, 2, 5))
box_1 = TFBoxTensor(tensor1)
box_1 = TFBoxTensor(tensor2)
box_1
box_2

# Intersection of box_1 and box_2


BoxTensor(z=tensor([1.0000, 0.5000, 0.3333, 0.2500, 0.2000, 0.1667, 0.1429, 0.1250, 0.1111,
        0.1000, 0.0909, 0.0833, 0.0769, 0.0714, 0.0667, 0.0625, 0.0588, 0.0556,
        0.0526, 0.0500, 0.0476, 0.0455, 0.0435, 0.0417, 0.0400, 0.0385, 0.0370,
        0.0357, 0.0345, 0.0333, 0.0323, 0.0312, 0.0303, 0.0294, 0.0286, 0.0278,
        0.0270, 0.0263, 0.0256, 0.0250, 0.0244, 0.0238, 0.0233, 0.0227, 0.0222,
        0.0217, 0.0213, 0.0208, 0.0204, 0.0200, 0.0196, 0.0192, 0.0189, 0.0185,
        0.0182, 0.0179, 0.0175, 0.0172, 0.0169, 0.0167, 0.0164, 0.0161, 0.0159,
        0.0156, 0.0154, 0.0152, 0.0149, 0.0147, 0.0145, 0.0143, 0.0141, 0.0139,
        0.0137, 0.0135, 0.0133, 0.0132, 0.0130, 0.0128, 0.0127, 0.0125, 0.0123,
        0.0122, 0.0120, 0.0119, 0.0118, 0.0116, 0.0115, 0.0114, 0.0112, 0.0111,
        0.0110, 0.0109, 0.0108, 0.0106, 0.0105, 0.0104, 0.0103, 0.0102, 0.0101,
        0.0100], grad_fn=<MaximumBackward>),
Z=tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

### 4. Box Training - TODO (waiting for Tf version)
In the following example, we train a simple box `box_2` to require it to be completely contained inside another box
`box_1`. The training loop returns the best `box_2`.

In [79]:
# Training boxes

# Create data as tensors, and initialize two boxes, box_1 and box_2
tensor1 = tf.constant(np.random.rand(3, 2, 5))
tensor2 = tf.constant(np.random.rand(3, 2, 5))
box_1 = TFBoxTensor(tensor1)
box_1 = TFBoxTensor(tensor2)
box_1
box_2

learning_rate = 0.1

def train(box_1, box_2, optimizer, epochs=1):
    best_loss = int()
    best_box_2 = None
    for e in range(epochs):
        loss = log_soft_volume(box_2)-log_soft_volume(hard_intersection(box_1, box_2))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if best_loss < loss.item():
            best_loss = loss.item()
            best_box_2 = box_2
        print('Iteration %d, loss = %.4f' % (e, loss.item()))
    return best_box_2

optimizer =  torch.optim.SGD([data_y], lr=learning_rate)
train(box_1, box_2, optimizer, epochs=20)

Iteration 0, loss = 61.7071
Iteration 1, loss = 58.2051
Iteration 2, loss = 54.6527
Iteration 3, loss = 51.0442
Iteration 4, loss = 47.3736
Iteration 5, loss = 43.6348
Iteration 6, loss = 39.8212
Iteration 7, loss = 35.9260
Iteration 8, loss = 31.9714
Iteration 9, loss = 27.9444
Iteration 10, loss = 23.8155
Iteration 11, loss = 19.6192
Iteration 12, loss = 15.3355
Iteration 13, loss = 11.0073
Iteration 14, loss = 6.7032
Iteration 15, loss = 2.5618
Iteration 16, loss = 0.0000
Iteration 17, loss = 0.0000
Iteration 18, loss = 0.0000
Iteration 19, loss = 0.0000


BoxTensor(tensor([[ 9.0841e-01,  3.8041e-01,  2.0479e-01,  1.1735e-01,  6.4819e-02,
          2.9872e-02,  4.9503e-03, -1.3714e-02, -2.8212e-02, -3.9795e-02,
         -4.9260e-02, -5.7138e-02, -6.3795e-02, -6.9492e-02, -7.4423e-02,
         -7.8730e-02, -8.2524e-02, -8.5890e-02, -8.8896e-02, -9.1595e-02,
         -9.4031e-02, -9.6240e-02, -9.8251e-02, -1.0009e-01, -1.0178e-01,
         -1.0333e-01, -1.0476e-01, -1.0608e-01, -1.0730e-01, -1.0844e-01,
         -1.0950e-01, -1.1049e-01, -1.1141e-01, -1.1227e-01, -1.1308e-01,
         -1.1384e-01, -1.1455e-01, -1.1521e-01, -1.1584e-01, -1.1642e-01,
         -1.1698e-01, -1.1750e-01, -1.1798e-01, -1.1844e-01, -1.1887e-01,
         -1.1928e-01, -1.1966e-01, -1.2001e-01, -1.2035e-01, -1.2066e-01,
         -1.2095e-01, -1.2122e-01, -1.2147e-01, -1.2169e-01, -1.2191e-01,
         -1.2210e-01, -1.2227e-01, -1.2242e-01, -1.2256e-01, -1.2268e-01,
         -1.2278e-01, -1.2286e-01, -1.2292e-01, -1.2296e-01, -1.2299e-01,
         -1.2299e-01, -1.229